language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
gemfile:
- Gemfile
cache: bundler
script: "bundle exec rspec"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libzmq3
  - sudo apt-get install libzmq3-dev
